### ISSUE TITLE
Define the database schema

### ISSUE THREAD

**Issue by doyonghoon** [Shmaug/YouSeeSD#29]
Tour — a global model under each unique User object. Only used in pre-tour screens.

- String :: tourId
- String :: title
- String :: subtitle
- String :: imageUrl
- int :: estimatedTime
- [Location]
    - String :: locationId
    - String :: title
    - String :: subtitle
    - String :: imageUrl
    - double :: latitude
    - double :: longitude
- [PathPoint]
    - double :: latitude
    - double :: longitude
    - [PathPoint] :: neighbors
- [Theme] — only for internal uses
    - String :: themeId
    - String :: label
    - [Tag]
        - String :: tagId
        - String :: label
        - boolean :: selected

LocationGroupTag — only used in CreateTourActivity

- name
- [Location]

User

- [TourId]

Feedback

- String :: feedbackId <auto-generated>
- String :: tourId
- String :: userId
- String :: message
- int :: rating

**Comment by jatotheson** [comment]
**Database Schema**

User
- //String :: userKey
- Tour [] :: userTours
- //Feedback [] :: userFeedback

Tour
- int :: tourId //could be String type
- String :: tourName
- String :: title
- String :: summary
- String :: imageUrl
- double [] :: themeVector //size of 13 for now
- ArrayList<Location> :: locations


Location
- int :: locationId //could be String type
- String :: title
- String :: subtitle
- String :: imageUrl
- String :: description
- **String :: builtin**
- **String :: seats**
- **String :: courses**
- double :: longitude
- double :: latitude


Theme (Fitness, Social, Engineering, …) //size of 13 for now
- int :: themeId //will be int type
- String :: themeName
- //double :: themeValue

TourSet
- ArrayList<Tour> allTours

//Feedback
- int :: feedbackId //could be String type
- int :: matchingTourId //could be String type
- String :: userId
- //String :: message
- int :: rating
